hw2
sreznick/kotlin-hse-2022 pull request #24
Opened 2022-11-12 18:43 UTC by GermanRandle

Андосов Герман М3239

2023-01-12 19:04 UTC, Shashulovskiy requested changes

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> fold(base: U, f: (U, T) -> U): U {
fixed

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun filter(f: (T) -> Boolean): FList<T> {
fixed

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> map(f: (T) -> U): FList<U> {
fixed

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +    fun <T> FList<T?>.head(): T? = if (this is FList.Cons) head else null
fixed

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/FList.kt
>  fun <T> flistOf(vararg values: T): FList<T> {
fixed

2023-01-13 20:42 UTC, GermanRandle commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +            if (sum.first != null) {
fixed

2023-01-16 09:50 UTC, Shashulovskiy approved these changes

2023-01-18 18:45 UTC, closed without merging