hw2
sreznick/kotlin-hse-2022 pull request #27
Opened 2022-11-13 16:09 UTC by TsenreD

Дягин Эрнест Александрович, КТ ИТМО М32391

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +    return firstImpl(0)
Поправил flistOf, остальные аналогично, просто сил уже нет после экзамена дописывать

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +            }
+

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +                return FList.Cons(first.head(), mergeTrees(first.tail(), second))
+

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/BinomialTree.kt
> +            return other.plus(this)
+

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/BinomialTree.kt
> +            return other.plus(this)
+

2023-01-24 11:51 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +
+

2023-01-24 11:52 UTC, TsenreD commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +                    val cons = state as Cons
+

2023-01-24 11:52 UTC, TsenreD commented
Прошу зачесть это домашнее задание

2023-01-26 13:49 UTC, FireF0xIl commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +    return firstImpl(0)
Исправление за 1 минус сойдет

2023-01-26 13:50 UTC, FireF0xIl requested changes
В принципе дз по баллам засчитано

2023-02-09 12:11 UTC, closed without merging