Hw3
sreznick/kotlin-hse-2022 pull request #44
Opened 2022-12-11 10:38 UTC by TsenreD

Дягин Эрнест Александрович, КТ ИТМО М32391
Домашная работа 3

2023-01-15 15:53 UTC, Shashulovskiy requested changes
В целом неплохо. Первое решение которое я увидел, что генерирует валидный csv файл

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/AboutSnapshot.kt
> +package homework03
Мне не нравится что у тебя все файлы лежат в корне, давай разобьем по пакетам

-0.5

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/HotSnapshot.kt
> +            author: String, @JsonSetter("created") datePublished: Double,
Давай 1 аргумент 1 строчка, так проще читать

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +    append("\n")
Здесь и ниже \n лучше вносить в функции

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +    val kClass = value.javaClass.kotlin
IDE правильно подсказывает что это можно заинлайнить

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +    append("")
Что конкретно делает append пустой строки?

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +
Убери пожалуйста лишние пустые строки

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +    val file = cwd[fileName].open(VfsOpenMode.CREATE_OR_TRUNCATE)
Лушче .use

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +    suspend fun getTopic(name: String): TopicSnapshot {
Функция должна быть приватной

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val client = createHttpClient()
Может лучше не создавать HTTP клиент на каждый вызов функции?

-0.5

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val aboutTopicJSON = client.getJsonString("https://www.reddit.com/r/$name/about.json")
URL лучше вынести в константу, более того, вынести логику построения урлов в отдельный класс

-0.5

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +    suspend fun getComments(title: String): CommentSnapshot {
Функция должна быть приватной

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val snapList: List<HotSnapshot> = nodeList.map { mapper.readValue(it["data"]) }
Мне кажется ты никак не обрабатываешт ошибки парсинга. Это не версионированное апи

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val jsonString = client.request(
Почему ты не используешь свой метод getJsonString?

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/App.kt
> +    args.forEach {
Без входных аргументов программа просто завершается. В таком случае лучше выводить usage

-0.25

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/App.kt
> +
Давай уберем лишние пустые строки

2023-01-15 15:53 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +package homework03
Правильнее будет назвать файл CSVWriter

2023-01-24 11:57 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/App.kt
> +
+

2023-01-24 12:06 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +package homework03
+

2023-01-24 12:07 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val client = createHttpClient()
+

2023-01-24 12:08 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +
+

2023-01-24 12:10 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/WriterCSV.kt
> +    append("")
Ничего...
Видимо, я не убрал этот момент из данного нам шаблонного кода

2023-01-24 12:10 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/HotSnapshot.kt
> +            author: String, @JsonSetter("created") datePublished: Double,
+

2023-01-24 12:15 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/AboutSnapshot.kt
> +package homework03
+

2023-01-24 12:21 UTC, TsenreD commented on homework03/app/src/main/kotlin/homework03/RedditClient.kt
> +        val aboutTopicJSON = client.getJsonString("https://www.reddit.com/r/$name/about.json")
Не очень понял, для чего здесь выносить в константу, но логику построения вынес

2023-01-24 12:24 UTC, TsenreD commented
Прошу зачесть это домашнее задание

2023-02-09 12:11 UTC, closed without merging