Smirnov Dmitrii ITMO M32361 HW3
sreznick/kotlin-hse-2022 pull request #47
Opened 2022-12-11 18:38 UTC by smirnovdm2107

2023-01-21 16:24 UTC, Shashulovskiy requested changes

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/model/Dtos.kt
> +    private val created: Long,
Зачем ты стал делать эти поля приватными?

-0.25

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/model/Dtos.kt
> +open class CommentDTO(
Мне не нравится идея хранить все DTO в одном классе. У этого есть как минимум несколько проблем:
1. Когда несколько людей захотят в этот файл что-то добавить они словят мерж конфликты
2. Файлы удобнее открывать поиском по файлам а не полнотекстовым поиском
3. В одном файле нельзя сделать разделение по сущностям

-0.5

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/csv/csv.kt
> +    append("\n")
Здесь и ниже \n лучше вносить в функции

-0.25

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/csv/csv.kt
> +    val kClass = value.javaClass.kotlin
IDE правильно подсказывает что это можно заинлайнить

-0.25

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/csv/csv.kt
> +    append("")
Что конкретно делает append пустой строки?

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditHandler.kt
> +interface RedditHandler {
Мне не очень нравится структура твоих файлов. Ты хорошо начал, вынес dto и csv в отдельные пакеты, но дальше нужно было работу с реддитом тоже вынести в отдельный пакет и т.д

-0.5

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditHandlerImpl.kt
> +            HttpClient.newBuilder().build().send(
Не надо создавать клиент на каждый вызов, его надо создать 1 раз

-0.5

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditHandlerImpl.kt
> +fun main(args: Array<String>) = runBlocking {
main точно должен быть не в этом файле

-0.5

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditHandlerImpl.kt
> +    args.map{redditHandler.getTopicWithComments(it)}.forEachIndexed { index, topicWithComments ->
Без входных аргументов программа просто завершается. В таком случае лучше выводить usage

-0.25

2023-01-21 16:24 UTC, Shashulovskiy commented on homework03/app/src/main/kotlin/homework03/RedditHandlerImpl.kt
> +        File("./${args[index]}--topics.csv").toVfs()
Работу с файлами надо бы вынести в отдельный класс

-0.5

2023-01-26 13:46 UTC, smirnovdm2107 commented on homework03/app/src/main/kotlin/homework03/RedditHandlerImpl.kt
> +    args.map{redditHandler.getTopicWithComments(it)}.forEachIndexed { index, topicWithComments ->
Что такое usage?

2023-02-07 17:55 UTC, closed without merging