ITMO Абрамов Илья Дмитриевич ДЗ-2
sreznick/kotlin-hse-2022 pull request #72
Opened 2022-12-25 20:49 UTC by IlyaAbramovv

Дата коммита неправильная. Последний коммит был тут f65d5d7095d6beba2b30c9dcd75f0d717016c98d

2023-01-18 16:33 UTC, FireF0xIl requested changes

2023-01-19 19:35 UTC, IlyaAbramovv commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +    return flistOfFromIndex(0, *values)
Исправил, переписав функции под tailrec

2023-01-19 19:35 UTC, IlyaAbramovv commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +            heap1.plus(heap2)
Исправил

2023-01-19 19:35 UTC, IlyaAbramovv commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +            ): FList<BinomialTree<T>?> {
Исправил

2023-01-19 19:35 UTC, IlyaAbramovv commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +            get() = 1 + tail.size
Исправил

2023-01-19 20:33 UTC, FireF0xIl approved these changes

2023-01-21 18:16 UTC, closed without merging